import 'dart:math';
import 'package:goodthings_app_project/models/good_things_model.dart';
import '../utils/database_helper.dart';

List<String> generateRandomGoodThings() {
  List<String> goodThings = [
    'Bantu orang tua di rumah',
    'Mengajak teman untuk olahraga',
    'Donasi ke panti asuhan',
    'Menyapa tetangga dengan ramah',
    'Mengurangi penggunaan plastik',
    'Membantu orang tua',
    'Menyumbangkan pakaian lama',
    'Menjadi relawan di panti asuhan',
    'Membersihkan lingkungan sekitar',
    'Mengajari anak-anak membaca',
    'Menanam pohon',
    'Menyumbangkan buku',
    'Mengunjungi rumah sakit',
    'Menyebarkan kebahagiaan dengan senyuman',
    'Mengirim kartu ucapan terima kasih',
    "Menyapa orang dengan senyuman.",
    "Memberi pujian tulus kepada seseorang.",
    "Membantu orang tua atau lansia menyeberang jalan.",
    "Memberikan tempat duduk di transportasi umum kepada yang lebih membutuhkan.",
    "Membuang sampah pada tempatnya.",
    "Mendaur ulang barang-barang yang bisa didaur ulang.",
    "Menghemat energi dengan mematikan lampu yang tidak diperlukan.",
    "Menggunakan air dengan bijak.",
    "Membawa tas belanja sendiri untuk mengurangi penggunaan plastik.",
    "Menggunakan transportasi umum atau berbagi kendaraan untuk mengurangi polusi.",
    "Menulis catatan atau surat cinta kepada orang tersayang.",
    "Membantu teman atau keluarga yang sedang kesulitan.",
    "Mengunjungi orang yang sakit atau membutuhkan.",
    "Mengucapkan terima kasih dengan tulus.",
    "Menyumbangkan pakaian atau barang-barang yang tidak terpakai.",
    "Memberi makan hewan jalanan.",
    "Membantu tetangga dengan pekerjaan rumah tangga.",
    "Memberikan waktu untuk mendengarkan keluh kesah seseorang.",
    "Menjadi sukarelawan di acara komunitas.",
    "Menanam pohon atau tanaman.",
    "Mengadakan atau berpartisipasi dalam kegiatan amal.",
    "Menghargai pendapat orang lain.",
    "Berbagi makanan dengan yang membutuhkan.",
    "Menyebarkan informasi yang bermanfaat.",
    "Membaca buku kepada anak-anak.",
    "Mengucapkan selamat pagi kepada orang yang ditemui.",
    "Menulis ulasan positif untuk bisnis atau layanan yang baik.",
    "Memasak untuk keluarga atau teman.",
    "Membersihkan area umum di lingkungan sekitar.",
    "Mendonasikan darah.",
    "Memberikan tempat duduk di ruang tunggu kepada yang lebih membutuhkan.",
    "Membantu mengangkat barang berat untuk orang lain.",
    "Menyediakan payung untuk orang yang kehujanan.",
    "Memberikan pujian kepada rekan kerja.",
    "Menghibur teman yang sedang sedih.",
    "Menyumbangkan buku ke perpustakaan atau sekolah.",
    "Mengirim pesan penyemangat kepada teman.",
    "Membayar minuman atau makanan seseorang secara anonim.",
    "Mengajar anak-anak di lingkungan sekitar.",
    "Menghargai waktu orang lain dengan datang tepat waktu.",
    "Membantu menyusun rak di perpustakaan.",
    "Mengambil sampah di pantai atau taman.",
    "Meminjamkan peralatan kepada tetangga.",
    "Menjadi mentor bagi seseorang yang membutuhkan bimbingan.",
    "Mengunjungi panti jompo dan berbicara dengan penghuni.",
    "Menjaga kebersihan toilet umum.",
    "Memberikan tips yang baik kepada pelayan.",
    "Memasak makanan sehat untuk keluarga.",
    "Mengikuti program donasi rutin.",
    "Membantu anak-anak dengan pekerjaan rumah mereka.",
    "Mengirimkan bunga kepada seseorang tanpa alasan khusus.",
    "Menawarkan bantuan kepada ibu dengan anak kecil.",
    "Mengirimkan kartu ucapan terima kasih.",
    "Menghibur orang yang baru kehilangan.",
    "Menyediakan waktu untuk berkumpul dengan keluarga.",
    "Mengadakan pertemuan dengan teman lama.",
    "Mengirimkan pesan penyemangat kepada rekan kerja.",
    "Menyediakan makanan bagi tunawisma.",
    "Menjaga pintu terbuka untuk orang lain.",
    "Menyumbangkan mainan ke panti asuhan.",
    "Mengorganisir kegiatan kebersihan lingkungan.",
    "Membantu menyiapkan acara komunitas.",
    "Menghibur anak-anak dengan aktivitas kreatif.",
    "Menjadi pendengar yang baik.",
    "Mengirimkan donasi kepada organisasi yang membutuhkan.",
    "Membantu orang menemukan jalan.",
    "Menyediakan air minum bagi pelari di acara maraton.",
    "Mengunjungi tetangga yang tinggal sendirian.",
    "Mengadakan acara fundraising untuk amal.",
    "Membantu seseorang mengatasi masalah teknis dengan perangkat elektronik.",
    "Menulis artikel atau blog yang memberikan informasi positif.",
    "Mengajar orang lain keterampilan yang dimiliki.",
    "Menyediakan transportasi bagi yang membutuhkan.",
    "Mengajarkan cara berkebun kepada anak-anak.",
    "Membantu teman pindahan rumah.",
    "Mengirimkan makanan kepada petugas kesehatan.",
    "Mengajarkan literasi kepada yang kurang beruntung.",
    "Menyediakan sarapan bagi orang yang membutuhkan.",
    "Menjaga anak-anak tetangga saat mereka bekerja.",
    "Memberikan konsultasi gratis di bidang keahlian.",
    "Membantu membersihkan tempat ibadah.",
    "Mengadakan penggalangan dana untuk bencana alam.",
    "Membantu orang mengisi formulir atau dokumen.",
    "Mengirimkan bingkisan kepada petugas layanan publik.",
    "Menawarkan tumpangan kepada teman atau kolega.",
    "Menyediakan makanan ringan bagi pekerja yang lembur.",
    "Mengorganisir acara seni atau musik di komunitas.",
    "Menyumbangkan peralatan olahraga ke sekolah.",
    "Mengajarkan keterampilan memasak kepada anak-anak.",
    "Membuat masker kain dan membagikannya.",
    "Menjadi pemandu wisata lokal bagi wisatawan.",
    "Menyediakan waktu untuk mendengarkan cerita lansia.",
    "Mengirimkan paket perawatan kepada tentara.",
    "Mengajarkan kursus online gratis.",
    "Membantu mengatur perpustakaan sekolah.",
    "Menyediakan makanan bagi anak-anak yang kelaparan.",
    "Menawarkan bantuan kepada ibu baru.",
    "Membuat dan menyebarkan poster positif di lingkungan.",
    "Mengajarkan keterampilan kerajinan tangan kepada anak-anak.",
    "Memberikan dukungan moral kepada yang sedang menghadapi ujian atau tantangan besar."
  ];

  // Mengacak daftar dan mengembalikan satu elemen acak
  goodThings.shuffle();
  return goodThings.take(1).toList(); // Mengambil satu tantangan
}

Future<void> saveRandomGoodThing(String userId, String goodThing) async {
  GoodThing newGoodThing = GoodThing(
    id: 0, // Auto-increment ID
    userId: userId,
    description: goodThing,
    status: 'Terlewat', // Default status
  );

  await DatabaseHelper().insertGoodThing(newGoodThing);
}
